# Generated by Django 5.0.8 on 2024-08-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
