# Generated by Django 5.0.8 on 2024-10-24 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_producto_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.producto')),
            ],
        ),
    ]
